//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;

namespace SosExporter.Ogc {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true, Namespace="http://www.opengis.net/ows/1.1")]
    [XmlRoot(Namespace="http://www.opengis.net/ows/1.1", IsNullable=false)]
    public partial class ExceptionReport {
        
        private ExceptionType[] exceptionField;
        
        private string versionField;
        
        private string langField;
        
        /// <remarks/>
        [XmlElement("Exception")]
        public ExceptionType[] Exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://www.opengis.net/ows/1.1")]
    [XmlRoot("Exception", Namespace="http://www.opengis.net/ows/1.1", IsNullable=false)]
    public partial class ExceptionType {
        
        private string[] exceptionTextField;
        
        private string exceptionCodeField;
        
        private string locatorField;
        
        /// <remarks/>
        [XmlElement("ExceptionText")]
        public string[] ExceptionText {
            get {
                return this.exceptionTextField;
            }
            set {
                this.exceptionTextField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string exceptionCode {
            get {
                return this.exceptionCodeField;
            }
            set {
                this.exceptionCodeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string locator {
            get {
                return this.locatorField;
            }
            set {
                this.locatorField = value;
            }
        }
    }
}
